name: Auto Deploy on Push

on:
  push:
    branches:
      - master  # Change to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Server
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no root@158.220.96.121 << 'EOF'
            source ~/.bashrc
            cd Travista/TravistaBD
            git pull
            pm2 reload server
          EOF
